from __future__ import annotations

from dataclasses import dataclass
from typing import Callable, Protocol


SessionCallback = Callable[[str], None]
PowerCallback = Callable[[str], None]


@dataclass
class StartupResult:
    ok: bool
    enabled: bool
    error: str | None = None
    command: str | None = None


class Platform(Protocol):
    def idle_seconds(self) -> float: ...
    def boot_id(self) -> str: ...
    def hostname(self) -> str: ...
    def user_logged_in(self) -> bool: ...
    def session_locked(self) -> bool: ...
    def enable_startup(self, command: str) -> StartupResult: ...
    def disable_startup(self) -> StartupResult: ...
    def startup_enabled(self) -> bool: ...
    def startup_command(self) -> str | None: ...
    def poll_session(self) -> str | None: ...
    def notify_session(self, callback: SessionCallback | None) -> None: ...
    def notify_power(self, callback: PowerCallback | None) -> None: ...
